### ISSUE TITLE
百度网盘的预训练模型压缩文件好像损坏了

### ISSUE THREAD

**Issue by forestbat** [LZhenShi/WIDFCN#1]
![图片](https://github.com/LZhenShi/WIDFCN/assets/23413915/d4f52516-6fc7-4c40-9ecf-77943f47f456)
![图片](https://github.com/LZhenShi/WIDFCN/assets/23413915/0896bf78-658b-4f7d-94c2-324d6e21f712)
麻烦补档一下，感激不尽。

**Comment by LZhenShi** [comment]
无需解压，weights = "your_path/WIDFCN-model.pth.tar"

**Comment by ChaiCH2026** [comment]
也可以用windows 的zip解压。
